environment:
  PYTHON_DIR: C:\Python35-x64
  VENV_BUILD_DIR: c:\projects\silx\venv_build

build_script:
- SET PATH=%PYTHON_DIR%;%PYTHON_DIR%\Scripts;%PATH%
- pip install --upgrade setuptools
- python -m pip install --upgrade pip
- pip install --upgrade virtualenv
- pip install virtualenv
- virtualenv --clear %VENV_BUILD_DIR%
- '%VENV_BUILD_DIR%\Scripts\activate.bat'
- pip install wheel
- pip install --trusted-host www.silx.org --find-links http://www.silx.org/pub/wheelhouse/ numpy
- python ci\info_platform.py

test: off
